### ISSUE TITLE
How to make it work with babel?

### ISSUE THREAD

**Issue by waghcwb** [vercel/webpack-asset-relocator-loader#92] opened 2020-07-11 13:56 UTC
I'm trying to use [escpos](https://www.npmjs.com/package/escpos) module with Electron. But some of the main js file uses class properties so I get this error:

![image](https://user-images.githubusercontent.com/6169950/87225665-2cdcc300-c365-11ea-8aae-5b841f0d2f0c.png)

How I can handle this with babel?

**Comment by guybedford** [comment] 2020-07-11 13:59
It looks like you are using a fork of webpack-asset-relocator-loader here by @marshallofsound? This should work with the latest version from the original @vercel/webpack-asset-relocator-loader.

Try upgrading and confirming the exact latest version of this project.

**Comment by waghcwb** [comment] 2020-07-11 17:32
Hi @guybedford, I removed Marshall's version from the project, and updated with vercel version

`package.json`
```json
"@zeit/webpack-asset-relocator-loader": "^0.7.2",
```

![image](https://user-images.githubusercontent.com/6169950/87230044-5b699680-c383-11ea-90a4-5b9147c6165d.png)

**Comment by guybedford** [comment] 2020-07-12 12:19
Actually the parse error is not being thrown by this project, but rather your own webpack configuration.

You need to configure webpack to support class fields. See eg something like https://stackoverflow.com/questions/55661413/how-to-add-the-class-properties-plugin-to-webpack for configuring Webpack properly here.

Closing as the issue is unrelated to this plugin but rather a Webpack / Babel / Acorn configuration one.

**Closed by guybedford** 2020-07-12 12:19 UTC
